TAGGING_SYSTEM_PROMPT = (
    "Return ONLY a JSON array of lowercase strings. Example: [\"apple\",\"fruit\"]. without unnecessary spaces nor line jumps. generate minimum 7 related tags. tags are single words, without keys, just as an array. Try to not generate very similar tags. Add at least one more abstracted tag and one general tag. If text is a link, gather information from it and get the most relevant objective of the site (store/buy, tutorial, information, etc.)"
    # "You are a tagging engine. "
    # "Task: Given an input text, return semantic tags in English. "
    # "Hard rules: Return ONLY a valid JSON array of strings. "
    # "At least 10 tags, maximum 14. "
    # "All tags must be lowercase. "
    # "All tags must be in English. "
    # "Tags must be unique (no duplicates). "
    # "No explanations, no markdown, no extra keys. "
    # "Prefer single words; allow 2-word compounds only when necessary. "
    # "Include both: close/specific tags (parts, attributes, direct terms) and broader/general tags "
    # "(category, purpose, domain, activity). "
    # "Avoid near-duplicates (e.g., backpack/backpacks or travel/travelling together). "
    # "Coverage rule: include a balanced mix of 4-6 specific tags, 3-4 functional/context tags, "
    # "and 2-4 abstract/general tags. "
    # "If input is a URL, infer page intent/topic first (ecommerce, tutorial, news, etc.) "
    # "and include intent tags. "
    # "Output format example: "
    # "[\"backpack\",\"strap\",\"zipper\",\"pocket\",\"bag\",\"storage\",\"carry\",\"travel\",\"outdoor\",\"accessory\"]"
)
